<?php
/**
 * Plugin Name: Head and Footer Scripts Inserter
 * Plugin URI: https://github.com/ArthurGareginyan/header-and-footer-scripts-inserter
 * Description: Easily add your scripts to the WordPress website's head and footer sections. This is a must have tool for authors and website's owners.
 * Author: Arthur Gareginyan
 * Author URI: http://www.arthurgareginyan.com
 * Version: 3.0.1
 * License: GPL3
 * Text Domain: header-and-footer-scripts-inserter
 * Domain Path: /languages/
 *
 * Copyright 2016 Arthur Gareginyan (email : arthurgareginyan@gmail.com)
 *
 * This file is part of "Head and Footer Scripts Inserter".
 *
 * "Head and Footer Scripts Inserter" is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * "Head and Footer Scripts Inserter" is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with "Head and Footer Scripts Inserter".  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Define constants
 *
 * @since 2.0
 */
defined('HFSINS_DIR') or define('HFSINS_DIR', dirname(plugin_basename(__FILE__)));
defined('HFSINS_BASE') or define('HFSINS_BASE', plugin_basename(__FILE__));
defined('HFSINS_URL') or define('HFSINS_URL', plugin_dir_url(__FILE__));
defined('HFSINS_PATH') or define('HFSINS_PATH', plugin_dir_path(__FILE__));

/**
 * Register text domain
 *
 * @since 2.0
 */
function HFScriptsIns_textdomain() {
	load_plugin_textdomain( 'header-and-footer-scripts-inserter', false, HFSINS_DIR . '/languages/' );
}
add_action( 'init', 'HFScriptsIns_textdomain' );

/**
 * Print direct link to "Head and Footer Scripts Inserter" admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the "Head and Footer Scripts Inserter" admin page
 *
 * @since  2.0
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function HFScriptsIns_settings_link( $links ) {
	$settings_page = '<a href="' . admin_url( 'options-general.php?page=header-and-footer-scripts-inserter.php' ) .'">' . __( 'Settings', 'header-and-footer-scripts-inserter' ) . '</a>';
	array_unshift( $links, $settings_page );
	return $links;
}
add_filter( "plugin_action_links_".HFSINS_BASE, 'HFScriptsIns_settings_link' );

/**
 * Register "Head and Footer Scripts Inserter" submenu in "Settings" Admin Menu
 *
 * @since 2.0
 */
function HFScriptsIns_register_submenu_page() {
	add_options_page( __( 'Head and Footer Scripts Inserter', 'header-and-footer-scripts-inserter' ), __( 'Head and Footer Scripts Inserter', 'header-and-footer-scripts-inserter' ), 'manage_options', basename( __FILE__ ), 'HFScriptsIns_render_submenu_page' );
}
add_action( 'admin_menu', 'HFScriptsIns_register_submenu_page' );

/**
 * Attach Settings Page
 *
 * @since 2.0
 */
require_once( HFSINS_PATH . 'inc/php/settings_page.php' );

/**
 *  Load scripts and style sheet for settings page
 *
 * @since 3.0
 */
function HFScriptsIns_load_scripts($hook) {

    // Return if the page is not a settings page of this plugin
    if ( 'settings_page_header-and-footer-scripts-inserter' != $hook ) {
        return;
    }

    // CodeMirror
    wp_enqueue_style('codemirror_style', HFSINS_URL . 'inc/lib/codemirror/codemirror.css');
    wp_enqueue_script('codemirror', HFSINS_URL . 'inc/lib/codemirror/codemirror.js');
    wp_enqueue_script('codemirror-htmlmixed', HFSINS_URL . 'inc/lib/codemirror/mode/htmlmixed.js');
    wp_enqueue_script('codemirror-javascript', HFSINS_URL . 'inc/lib/codemirror/mode/javascript.js');
    wp_enqueue_script('codemirror-xml', HFSINS_URL . 'inc/lib/codemirror/mode/xml.js');
    wp_enqueue_script('codemirror-css', HFSINS_URL . 'inc/lib/codemirror/mode/css.js');
    wp_enqueue_script('codemirror-active-line', HFSINS_URL . 'inc/lib/codemirror/addons/active-line.js');
    
    // JS functions
    wp_enqueue_script('js-functions', HFSINS_URL . 'inc/js/main.js', array(), false, true);

    // Style sheet
    wp_enqueue_style('styles', HFSINS_URL . 'inc/css/admin.css');
}
add_action('admin_enqueue_scripts', 'HFScriptsIns_load_scripts');

/**
 * Register settings
 *
 * @since 0.1
 */
function HFScriptsIns_register_settings() {
	register_setting( 'HFScriptsIns_settings_group', 'HFScriptsIns_settings' );
}
add_action( 'admin_init', 'HFScriptsIns_register_settings' );

/**
 * Inject scripts in the frontend head and footer
 *
 * @since 1.0
 */
add_action('wp_head', 'HFScriptsIns_inject_head_beginning', 0);
add_action('wp_head', 'HFScriptsIns_inject_head_end', 1000);
add_action('wp_footer', 'HFScriptsIns_inject_footer_beginning', 0);
add_action('wp_footer', 'HFScriptsIns_inject_footer_end', 1000);

/**
 * Prepare scripts for outputing
 *
 * @since 1.0
 */
function HFScriptsIns_inject_head_beginning() { HFScriptsIns_output('header_beginning'); }
function HFScriptsIns_inject_head_end() { HFScriptsIns_output('header_end'); }
function HFScriptsIns_inject_footer_beginning() { HFScriptsIns_output('footer_beginning'); }
function HFScriptsIns_inject_footer_end() { HFScriptsIns_output('footer_end'); }

/**
 * Outputs the given setting, if conditions are met
 *
 * @param string $option Option Name
 * @return output
 *
 * @since 3.0
 */
function HFScriptsIns_output($option) {

    // Ignore admin, feed, robots or trackbacks
    if (is_admin() || is_feed() || is_robots() || is_trackback()) {
        return;
    }

    // Read options from BD and declare variables
    $options = get_option( 'HFScriptsIns_settings' );
    $data = $options[$option];

    // If data is empty then exit
    if( empty( $data ) ){
        return;
    }

    // Add comments to output
    $data_out = "\n<!-- [BEGIN] Scripts added via Head-and-Footer-Scripts-Inserter plugin by Arthur Gareginyan. -->\n";
    $data_out .= $data;
    $data_out .= "\n<!-- [END] Scripts added via Head-and-Footer-Scripts-Inserter plugin by Arthur Gareginyan. -->\n\n";

    // Output
    echo $data_out;
}

/**
 * Delete options on uninstall
 *
 * @since 0.1
 */
function HFScriptsIns_uninstall() {
    delete_option( 'HFScriptsIns_settings' );
}
register_uninstall_hook( __FILE__, 'HFScriptsIns_uninstall' );

?>