<?php

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Register text domain
 *
 * @since 3.3
 */
function HFScriptsIns_textdomain() {
    load_plugin_textdomain( HFSINS_TEXT, false, HFSINS_DIR . '/languages/' );
}
add_action( 'init', 'HFScriptsIns_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 *
 * @since  3.3
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function HFScriptsIns_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=header-and-footer-scripts-inserter.php' ) .'">' . __( 'Settings', HFSINS_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_'.HFSINS_BASE, 'HFScriptsIns_settings_link' );

/**
 * Print additional links to plugin meta row
 *
 * @since 4.0
 */
function HFScriptsIns_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, 'header-and-footer-scripts-inserter.php' ) !== false ) {

        $new_links = array(
                           'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8A88KC7TFF6CS" target="_blank"><span class="dashicons dashicons-heart"></span> ' . __( 'Donate', HFSINS_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', 'HFScriptsIns_plugin_row_meta', 10, 2 );

/**
 * Register plugin's submenu in the "Settings" Admin Menu
 *
 * @since 4.0
 */
function HFScriptsIns_register_submenu_page() {
    add_options_page( __( 'Head and Footer Scripts Inserter', HFSINS_TEXT ), __( 'Head and Footer Scripts Inserter', HFSINS_TEXT ), 'manage_options', 'header-and-footer-scripts-inserter', 'HFScriptsIns_render_submenu_page' );
}
add_action( 'admin_menu', 'HFScriptsIns_register_submenu_page' );

/**
 * Register settings
 *
 * @since 4.0
 */
function HFScriptsIns_register_settings() {
    register_setting( 'HFScriptsIns_settings_group', 'HFScriptsIns_settings' );
    register_setting( 'HFScriptsIns_settings_group', 'HFScriptsIns_service_info' );
}
add_action( 'admin_init', 'HFScriptsIns_register_settings' );
